---
services:
    php:
        build: ./php/${PHP_VERSION}
        container_name: php
        volumes_from:
            - source
        links:
            - db
        environment:
            TZ: Europe/Moscow
        stdin_open: true
        tty: true
        networks:
            - bitrixdock
        restart: unless-stopped

    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: web_server
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:443:443'
        links:
            - php
        networks:
            - bitrixdock
        environment:
            TZ: Europe/Moscow
        stdin_open: true
        tty: true
        restart: unless-stopped

    db:
        build: ./${DB_SERVER_TYPE}
        container_name: db
        volumes:
            - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: Europe/Moscow
        command: mysqld --user=root --sql-mode=""
        networks:
            - bitrixdock
        stdin_open: true
        tty: true
        restart: unless-stopped

    source:
        image: alpine:latest
        container_name: source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - bitrixdock

volumes:
    db:
        driver: local
    cache:
        driver: local

networks:
    bitrixdock:
